<a href="https://colab.research.google.com/github/Varalakshmi-skab/datasciencelearning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
#1d array
l = [1,2,3,4,5]
print(l)
print("type of list",type(l))
#after converting into list
l = np.array(l)
print(l)
print("type of array",type(l))
print(l.ndim)

[1, 2, 3, 4, 5]
type of list <class 'list'>
[1 2 3 4 5]
type of array <class 'numpy.ndarray'>
1


In [ ]:
#creating 2d array
l1=[1,2,3,4,5]
l2=[3,4,5,6,7]
l3=[5,6,7,8,9]
l4=np.array([
    l1,
    l2,
    l3
])
print(l4)
print(l4.ndim)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]
2


In [ ]:
#creating 3d array
l1=[
    [1,2],
    [3,4]
]
l2=[
    [1,2],
    [3,4]
]
l3=np.array([
    l1,l2
])
print(l3)
print(l3.ndim)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3


In [ ]:
#different ways to create arrays

In [ ]:
#usung array
l=[1,2,3,4,5]
p=(1,2,3,4,5)
l=np.array(l)
p=np.array(p)
print("list converted into array")
print(l)
print("tuple converted into array")
print(p)

list converted into array
[1 2 3 4 5]
tuple converted into array
[1 2 3 4 5]


In [ ]:
#fromiter
l=[1,2,3,4,5]
arr=np.fromiter(l,dtype=int)
print(arr)

[1 2 3 4 5]


In [ ]:
#arange
l=np.arange(5)
print(l)
l=np.arange(1,9)
print(l)
l=np.arange(1,10,2)
print(l)

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [ ]:
arr=np.linspace(1,5,8)
print(arr)

[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]


In [ ]:
arr=np.empty((5,3))
print(arr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [ ]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


zeros ans ones we will use in the deep learning tech


In [ ]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]




#1. if we want to know the no. of rows and colomns we will use this ***shape*** property

#2. if we wnat to know the dimension of an array we will use ***ndim*** property

#3. if we want to know the datatype of an array we will use ***dtype*** property



In [ ]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.shape) #if we want to know the no. of rows and colomns we will use this shape property
print(arr.ndim) #if we wnat to know the dimension of an array we will use ndim property
print(arr.dtype) #if we want to know the datatype of an array we will use dtype property

[[1 2 3 4 5]
 [4 5 6 7 8]]
(2, 5)
2
int64




#* if i want to perform operation in colomns i use axis=0

#* if i want to perform operation in rows i use axis=1





In [ ]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[1 2 3 4 5]
 [4 5 6 7 8]]
[ 5  7  9 11 13]
[15 30]


In [ ]:
#indexing
l=[10,20,30,40,50]
arr=np.array(l)
print(arr[3])
print(arr[0])
print(arr[1])
print(arr[-1])

40
10
20
50


In [ ]:
l2=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(l2)
print(l2[0,0])
print(l2[2,2])
print(l2[1,0])
#     0 1 2
# 0->[1 2 3
# 1-> 4 5 6
# 2-> 7 8 9]
print(l2[0])
print(l2[1])
print(l2[2])
print(l2[:,0])
print(l2[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
4
[1 2 3]
[4 5 6]
[7 8 9]
[1 4 7]
[2 5 8]


In [ ]:
#slicing
#1[start:end:step]
#here end is exclusive
l=[1,2,3,4,5]
arr=np.array(l)
print(arr)
print(arr[0:2])
print(arr[0:5])
print(arr[1:5])
print(arr[0:5:2])
print(arr[1:])
print(arr[:4])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[2 3 4 5]
[1 3 5]
[2 3 4 5]
[1 2 3 4]


In [ ]:
#l=[row_start:row_end,col_start:col_end]
l=np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]
])
print(l)
print(l[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2]
 [4 5]]




#reshaping:changing an array from one dimension to another👇👇



In [ ]:
#reshaping:changing an array from one dimension to another
l=[1,2,3,4,5,6]
l=np.array(l)
print(l)
print(l.ndim)
new_arr=l.reshape(2,3)
print(new_arr)
print(new_arr.ndim)

[1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr=np.array([1,2,3,4,5])
arr.resize(2,3)
print(arr)

[[1 2 3]
 [4 5 0]]


In [ ]:
#broadcasting means automatically applying a single value to all elements of another array during mathematical operation
l=np.array([1,2,3,4,5])
print(l+5)

[ 6  7  8  9 10]


In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3])
arr2=np.array([10,20,30])
#addition
#1+10=11
#2+20=22
#3+30=33
print(arr1+arr2)
#subtraction
#10-1=9
#20-2=18
#30-3=27
print(arr2-arr1)
#multiplication
#10*1=10
#20*2=40
#30*3=90
print(arr1*arr2)
#division
#10/1=10
#20/2=10
#30/3=10
print(arr2/arr1)
print(arr2//arr1)
print(arr2%arr1)
print(arr1**2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[10 10 10]
[0 0 0]
[1 4 9]


#Aggregate functions:Functions used to summarize data.


In [5]:
#Aggregate functions:Functions used to summarize data.
l=np.array([10,20,30,40,50,60])
#add all elements=sum
print(np.sum(l))
#average
print(np.mean(l))
#minimum
print(np.min(l))
#maximum valu
print(np.max(l))
#standard deviation
print(np.std(l))
#variance
print(np.var(l))
#size of elements in the array
print(np.size(l))
#argmax:gives the index position of the largest value
print(np.argmax(l))
#argmin:gives the index position of the smallest value
print(np.argmin(l))
#applying square root
print(np.sqrt(l))

210
35.0
10
60
17.07825127659933
291.6666666666667
6
5
0
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


#Absolute function convert negative to positive

In [6]:
arr=np.array([-1,-2,-3,-4,-5])
print(np.abs(arr))

[1 2 3 4 5]


#Numpy rounding functions

In [7]:
arr=np.array([1.2,2.7,3.5,4.1,5.9])
#round: rounds values to nearest integer
#1.2->1
#2.7->3
#3.5->4
#4.1->4
#5.9->6
print(np.round(arr))

[1. 3. 4. 4. 6.]


In [8]:
arr=np.array([1.2,2.7,3.5,4.1,5.9])
#floor:it will always give lower integer value
#1.2->1
#2.7->2
#3.5->3
#4.1->4
#5.9->5
print(np.floor(arr))

[1. 2. 3. 4. 5.]
